# Generated by Django 6.0 on 2026-02-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_full_address_order_address_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
    ]
