# Generated by Django 6.0 on 2026-02-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_device_created_at_remove_device_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='gas_level',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='pm25',
        ),
    ]
